### PR TITLE
#158792524 Design Mockups for the App

### PR DESCRIPTION
**Pull request by moseskamira**
### What does this PR do?
The PR involves designing Mockups for the Application

### Description of the task

- Create a wireframes directory under the root directory of the project

- Design major screen flows of the application

- Add the wireframes to the created directory

- Link wireframes to README doc.

### Link To Navigable Mockups
https://www.justinmind.com/usernote/tests/39777996/39783299/39783301/index.html#/screens/d12245cc-1680-458d-89dd-4f0d7fb22724

### Relevant pivotal tracker story
[#158792524](https://www.pivotaltracker.com/story/show/158792524)

### Designed Mockups
List
profile
sharing

### CODE REVIEW

**Comment by evamaina** [comment]
seems you deleted the inbuilt files that come with Android once you create a new project.The design mockups should be part of your new project

**Comment by moseskamira** [comment]
> seems you deleted the inbuilt files that come with Android once you create a new project.The design mockups should be part of your new project

**Comment by moseskamira** [comment]
> seems you deleted the inbuilt files that come with Android once you create a new project.The design mockups should be part of your new project

No, I did not delete the built files but  since creating the project is another story on its own, I decide to use VS code to push the mockups, then am to clone the Repo when creating a Project using Android studio that I will have to set up today.

**Comment by evamaina** [comment]
LGTM

**Pull request merged**
